### ISSUE TITLE
Error While Unpublishing: entity undefined entity at index 0

### ISSUE THREAD

**Issue by SalilGavhankar** [contentful/contentful-space-sync#101]
I tried to sync following two spaces. 
**Source space** : w01sbxcs8tuo
**Destination space** : 6w3ci3275pfh

When destination space was empty content types and contents got created successfully (Well Done!). After this synchronization I added content type, content and deleted single content, asset from source and executed utility again. New content type and content were created successfully BUT the deletion is not getting synced in destination space. Getting following error

Error While Unpublishing: entity undefined entity at index 0
Error While deleting entity: undefined entity at index 0
 
It would be great if someone look into this issue.

**Comment by Khaledgarbaya** [comment]
Hi @SalilGavhankar ,
Did you use a sync token for the second sync ?
Also what version of the tool did you use ?

Best,
Khaled

**Comment by SalilGavhankar** [comment]
Hi Khaledgarbaya,

At the time of second sync, utility picked up the existing token that was created at the time of first sync.

Synchronizing content from w01sbxcs8tuo to 6w3ci3275pfhwith existing token from...

I am using version 4.1.2 of the utility.

Thanks for your reply.

**Comment by SalilGavhankar** [comment]
Hi @Khaledgarbaya 

Have you got change to look into this issue?

**Comment by Khaledgarbaya** [comment]
@SalilGavhankar ,
this could happen due to multiple reasons, like an entity didn't get unpublished in time. You could increase the waiting time for that by setting the `--pre-publish-delay`.

**Comment by SalilGavhankar** [comment]
Hi @Khaledgarbaya ,
I tried with by setting --pre-publish-delay to 50000. I have deleted content from source space and ran the tool. But still i m getting following error

info Error While Unpublishing: entity undefined entity at index 0
info Error While deleting entity: undefined entity at index 0

Please advice.

**Comment by Khaledgarbaya** [comment]
Hi @SalilGavhankar , can you create a ticket at our support so we can take a closer look at your spaces and seeing what is causing this problem.

**Comment by Khaledgarbaya** [comment]
@agarwalnikhil Sorry still couldn't reproduce it

**Comment by agarwalnikhil** [comment]
@Khaledgarbaya  any other alternative for this? Also i created a node utility to do the same where a form with these 4 fields is there (source id, destination id, delivery token and management token) and on submit the contentful sync will perform, I deployed the application on Heroku.
But as when we will restart the dyno in heroku, the token file will get deleted. And an error will be shown that your destination space already has some content please empty the space or provide token file.
Do you have any idea about this ?

**Comment by agarwalnikhil** [comment]
@Khaledgarbaya But then if i will run the utility for 4-5 spaces then everytime i need to fetch the token for respective space id(source and deestination) from db. Or it will automatically find the respective sync token from db?

**Comment by Khaledgarbaya** [comment]
@agarwalnikhil You will need to grab the token for each operation

**Comment by agarwalnikhil** [comment]
@Khaledgarbaya okay thanks. :)
