### ISSUE TITLE
Using as library fails without `syncTokenFile`

### ISSUE THREAD

**Issue by tnunes** [contentful/contentful-space-sync#103]
The `runSpaceSync` function is currently failing at the end of the sync process if the optional parameter `syncTokenFile` is not specified.

The following error is thrown:

```
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /Users/tnunes/work/Mindera/tui/tda.mbaas.node/node_modules/contentful-space-sync/dist/run-space-sync.js:110:22
```

Going through the code confirms that `fs.writeFileSync` is being given the value of `syncTokenFile`, which is `undefined` and causing the error.

**Comment by Khaledgarbaya** [comment]
Hi @tnunes,
Thanks for reporting I will check it out asap and sorry for the issue

Best,
Khaled

**Comment by Khaledgarbaya** [comment]
@tnunes can you provide a code snippet on how you used the tool as a library especially the object structure you passed in.
Best,
Khaled

**Comment by Khaledgarbaya** [comment]
it is not clear in the documentation but your options object should like something like this: 
```
{
  opts{
    managementToken: '',
    sourceSpace: '',
    destinationSpace: ''
  },
  syncTokenFile : 'TOKEN_FILE'
}
```

**Comment by tnunes** [comment]
Hi @Khaledgarbaya,

I left the example of how I'm using the library in https://github.com/contentful/contentful-space-sync/issues/102#issuecomment-261252389.

This specific issue refers to the fact that even though the `syncTokenFile` parameter is not required in the CLI version of the tool, it's currently being required when using it programatically as a library.

It's not documented as being required and I believe the library could either infer it automatically if not present (to something like ````contentful-space-sync-token-${sourceSpaceId}-to-${destSpaceId}````) or not write the file to disk at all.

**Comment by Khaledgarbaya** [comment]
Yeah this one i will fix, cli was setting it to pwd if it is not defined
but not for library ise, sorry about that i will work on that asap

**Comment by tnunes** [comment]
Hi @Khaledgarbaya,

#102 seems to be fixed.

The tool is not failing anymore, but I'm still seeing some errors related to #103:

```
info Published Entry 58Jpf7aT8IKAaayqCsGQAC
info Cannot write synckToen to fileSystem,  TypeError: path must be a string or Buffer
info Cannot write synckToen to fileSystem,      at TypeError (native)
info Cannot write synckToen to fileSystem,      at Object.fs.openSync (fs.js:640:18)
info Cannot write synckToen to fileSystem,      at Object.fs.writeFileSync (fs.js:1333:33)
info Cannot write synckToen to fileSystem,      at .../node_modules/contentful-space-sync/dist/run-space-sync.js:117:24
info Cannot write synckToen to fileSystem,   TypeError: path must be a string or Buffer
info Cannot write synckToen to fileSystem,      at TypeError (native)
info Cannot write synckToen to fileSystem,      at Object.fs.openSync (fs.js:640:18)
info Cannot write synckToen to fileSystem,      at Object.fs.writeFileSync (fs.js:1333:33)
info Cannot write synckToen to fileSystem,      at .../node_modules/contentful-space-sync/dist/run-space-sync.js:117:24
info Successfully sychronized the content and saved the sync token to:
  undefined
```

**Comment by Khaledgarbaya** [comment]
I guess getting the current working directory is not working in this case, I will fix it in a moment

**Comment by Khaledgarbaya** [comment]
@tnunes pushed a fix

**Comment by tnunes** [comment]
@Khaledgarbaya,

The fix still does not work :)

The last commit actually makes it worse. Using `process.cwd()` was the way to go, as `__dirname` will give you the directory where the `run-space-sync.js` file is, and that's never gonna be the place we want to store the sync token file in.

The problem is that in [line 21](https://github.com/contentful/contentful-space-sync/blob/f05706191b3930c098e1a74335bde7594babc780/lib/run-space-sync.js#L21) you are assigning the file path to `opts.syncTokenFile`, but then in lines [31](https://github.com/contentful/contentful-space-sync/blob/f05706191b3930c098e1a74335bde7594babc780/lib/run-space-sync.js#L31), [81](https://github.com/contentful/contentful-space-sync/blob/f05706191b3930c098e1a74335bde7594babc780/lib/run-space-sync.js#L81) and [85](https://github.com/contentful/contentful-space-sync/blob/f05706191b3930c098e1a74335bde7594babc780/lib/run-space-sync.js#L85), you are using the `syncTokenFile` constant, which is `undefined`.

The errors are being produced by the call to `fs.writeFileSync` in [line 81](https://github.com/contentful/contentful-space-sync/blob/f05706191b3930c098e1a74335bde7594babc780/lib/run-space-sync.js#L81).

**Comment by Khaledgarbaya** [comment]
😐 yeah, I totally missed that. ok I pushed the fix and reverted back using the `process.cwd()`

**Comment by tnunes** [comment]
It looks good to me now, apart from the small detail I mentioned in https://github.com/contentful/contentful-space-sync/pull/104/files#r89487379.

**Comment by Khaledgarbaya** [comment]
ok @tnunes the pull request will be released by next week. Thanks for all the feedback

**Comment by tnunes** [comment]
Perfect, thanks!

**Comment by Khaledgarbaya** [comment]
I am closing this issue now please follow the pull request for more changes. An if you have more issues or feedbacks please feel free to create a new issue
