### ISSUE TITLE
Conflict (409) after deleting an asset on destination space

### ISSUE THREAD

**Issue by bszatny** [contentful/contentful-space-sync#105]
Hello, I contact you because I get 409 error when trying to sync asset from my dev space to my production space. I accidentally deleted manualy an asset on destination space and when trying to launch sync on this asset I get a 409, thank you very much for your help.

**Comment by Khaledgarbaya** [comment]
Hi @bszatny,
Can you provide the log file or the output of the command line

Best,
Khaled

**Comment by agarwalnikhil** [comment]
@Khaledgarbaya Hi, I have 3 issues regarding this:-

1) I am not able to synchronize the deleted content from source space to destination space, In future, are you planning to add that in this utility? 
2) Can we increase the contentful rate limit, getting this error(You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan)
3) I created a node utility and deployed it to Heroku. But as Heroku wont allow to store the sync token file in its file system, so getting an error either empty the destination space or provide sync token file. As suggested by you, I can use the database but according to the mechanism it will search for the token file not in the db. I can store the token in db but how will I create a token file for that ?

**Comment by Khaledgarbaya** [comment]
@agarwalnikhil 
1. I don't think this will be added anytime soon, because it will involve more request to delete a contentType, so this will be a low priprity for us.

2. Unfortunately we can do that, there is `--rate-limt` and `--rate-limit-period` you can adjust them to not hit the rate limit. 

3. You can use the space-sync tool as a [library](https://github.com/contentful/contentful-space-sync#usage-as-a-library), grabbing the token and save it to the database in order to keep it around.

Hope That helps.

Best,
Khaled

**Comment by agarwalnikhil** [comment]
@Khaledgarbaya 
2) Can you just give an example of like how to define the time in --rate-limit , how the parameters need to be given for this.
3) I have tried to use this as library as well, but what needs to be passed in 'options'. Is it a dictionary, json file or json object? 

spaceSync(options).then((output) => {
  console.log('sync token', output.nextSyncToken)
})

**Comment by Khaledgarbaya** [comment]
@agarwalnikhil ,

For the rate limits params you can pass them as a command line vars like `contentful-space-sync --rate-limit 5 --rate-limit-period 2000 ....` or having a config file 
2)
```json
{
 "spaceId": "SPACE_ID",
 "managementToken": "MANAGEMENT_TOKEN",
 "rateLimit": 4,
 "rateLimitPeriod": 2000
}
``` 
and then executing `contentful-space-sync --config config.js`

the `rateLimit` means how many request to make per period of time which you can define it in ms using the `rateLimitPeriod`. 

3)
To use a library here is a snippet.
```js
var spaceSync = require('contentful-space-sync')
var options = {
opts:{
 "spaceId": "SPACE_ID",
 "managementToken": "MANAGEMENT_TOKEN",
 "rateLimit": 4,
 "rateLimitPeriod": 2000
}
}
spaceSync(options)
.then((output) => {
  console.log('sync token', output.nextSyncToken)
})
.catch((err) => {
  console.log('oh no! errors occurred!', err)
})
```
