### ISSUE TITLE
Question: Empty content(s) - Validation error

### ISSUE THREAD

**Issue by sofiekedvik** [contentful/contentful-space-sync#106]
All content-types are copied/synced to the destination space, but the content only displays the names correct and some are unpublished. Looking further, they are all empty inside even the published ones. The log file explains: validation error. I have indeed put some validation on some of the fields, but not all and not in every content-type. If I try run it again nothing is synced. 

Is there a work around on this? Also: I haven't tried the link-cleaner, since that error never occurred in my log.  Or is there something I might have missed?

**Comment by Khaledgarbaya** [comment]
Hi @sofiekedvik,
Can you maybe provide the log file,**Please make sure to remove any sensible informations like token and space id**, Also the version the space-sync tool version you are using 

Best,
Khaled

**Comment by sofiekedvik** [comment]
Hey @Khaledgarbaya!

I tried out some new things this passed time, a college of mine solved his issues with: and it turned out good! The spaces needed to have the same locales. I must have missed it some how. Too bad the error messages didn't say nothing about that. So all is good! 

Great job and thank you!

**Comment by Khaledgarbaya** [comment]
@sofiekedvik , glad it worked got you. I will close this issue for now and feel free to add a new one if you have an issue.
