### ISSUE TITLE
Appearances for the fields are not getting synced properly

### ISSUE THREAD

**Issue by ndrez** [contentful/contentful-space-sync#107]
After syncing a space to an empty one the appearance setting for a field is not getting synced properly. 

_Example:_ Short text field with an appearance "Dropdown" will be synced to new space with an appearance "Single line". Is this a known issue?

**Comment by Khaledgarbaya** [comment]
hi @ndrez ,

Unfortunately, this is not supported in the space sync tool. Alternatively you can use [contentful-export](https://github.com/contentful/contentful-export) and [contentful-import](https://github.com/contentful/contentful-import) to get the presentations synced.

Best,
Khaled
