### ISSUE TITLE
Node API (along with CLI)

### ISSUE THREAD

**Issue by jblock** [contentful/contentful-space-sync#40]
Hi! We'd like to tie this module to our Hubot instance (`!deploy content to production`), but unfortunately the CLI-only API is making that hard for us. Ideally a node-API would be exposed as well.

For example:

```js
var SpaceSync = require('contentful-space-sync')
var config = {/*...*/}
var options = {/*...*/}

module.exports = function(robot) {
  robot.respond(/something/i, function(msg) {
    var sync = new SpaceSync(options, config)
    sync.perform()
      .then(function(data) {
        // in happy land we'd also like to not have to write to the filesystem
        redis.set('content-sync-url', data.url}
        msg.send('Yay! Successful sync performed')
      })
      .catch(function(err) {
         console.error(err)
         msg.send('NOOOOO! Your sync did not work')
      })
  }
}
```

Let me know if you need me to provide more background about my use case! I'm happy to put out a PR for this work.

**Comment by trodrigues** [comment]
Hi Jason,

that makes a lot of sense and in fact the code is already written that way
internally. It mostly just needs that API to be documented and of course,
actually exposed.

I'll look into releasing this very soon.

**Comment by jblock** [comment]
Thanks @trodrigues! Let me know if I can help

**Comment by trodrigues** [comment]
Hi there. Sorry for not writing about this soon but it got a bit lost in holiday vacations and such.

Also it turned out not to be as simple as I expected due to the way babel polyfill was being used here, as well as in the dependent library which implements most of the actual logic.

It's now not using the polyfill anymore so anything using this as a library shouldn't risk having stuff polyfilled when the user doesn't expect it.

This is now available from 3.0.0.

**Comment by jblock** [comment]
Thanks @trodrigues! I'll let you know if we have any issues using it.

**Comment by trodrigues** [comment]
Hi @jblock 

I wanted to ask if you ended up building this hubot integration and if you published it somewhere. Someone else expressed interest in using a similar workflow and if it had been published that would be great.

**Comment by jblock** [comment]
Hey @trodrigues! We haven't got to it yet (the holidays and other projects got in the way), but when I do I will reach out/publish it somewhere

**Comment by trodrigues** [comment]
Ah great :) Let me know if you do, and I'll add it to our community tools list https://github.com/contentful-labs/awesome-contentful

**Comment by jblock** [comment]
Hi @trodrigues!

We're going through and implementing this right now. Would you accept a PR to output the sync token information as a return value of the `runSpaceSync` function? Our systems are constraining us from being able to write it to the filesystem.

**Comment by trodrigues** [comment]
Oh yeah, that didn't really cross my mind. Yes of course, go ahead.

**Comment by trodrigues** [comment]
Hey there,

I just pushed a version which exposes the token on the return value of the promise, and documented the usage of the library in the readme.

**Comment by jblock** [comment]
Sweet! Thanks @trodrigues
