### ISSUE TITLE
It's a question : Syncing Issues ..?

### ISSUE THREAD

**Issue by devsaik** [contentful/contentful-space-sync#42]
I created a new space(lets call it "playground") and I have a source space( lets call it "master") and I installed node module and created a sync-config.json file  and 

my JSON looks like this :
{
  "sourceSpace": "master-spaceId",
  "destinationSpace": "playground-spaceid",
  "sourceDeliveryToken": "I am not sure what goes in here..?",
  "destinationManagementToken": "playground-accesstoken-for-production",
  "sourceManagementToken" : "master-accesstoken-for-production"
}

I made some assumptions in the above properties .., does this look right to you and also can you let me know what goes in as sourcedeliverytoken

**Comment by JaviLorbada** [comment]
Let's asume you have the spaces within the same Organisation:

You could do the following:

```
{
   "sourceSpace": "master-spaceId",
   "destinationSpace": "playground-spaceid",
   "sourceDeliveryToken": https://app.contentful.com/spaces/{master-spaceId}/api/keys/",
   "managementToken" : "https://www.contentful.com/developers/docs/references/authentication/#the-management-api"
}
```

See the following screenshots to create a `sourceDeliveryToken`:
 
![screenshot 2015-12-24 12 48 03](https://cloud.githubusercontent.com/assets/1939155/11994357/2027b570-aa3d-11e5-8b07-13a61652a11b.png)
![screenshot 2015-12-24 12 49 59](https://cloud.githubusercontent.com/assets/1939155/11994356/201d76aa-aa3d-11e5-9fa0-ed0bb7ab8ab8.png)
![screenshot_2015-12-24_12_55_09](https://cloud.githubusercontent.com/assets/1939155/11994437/ad65fc0c-aa3e-11e5-9ef8-2c826c99bceb.png)

You can use the **production** key, I guess you can also use the **preview** one.

Hope that helps @devsaik :ok_hand:

**Comment by devsaik** [comment]
Thanks @JaviLorbada
