### ISSUE TITLE
Appearance is not copied

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-space-sync#49]
Missing Help Text and the Widget for how this field should be displayed

**Comment by trodrigues** [comment]
Unfortunately Contentful does not yet provide a public API for this so this isn't possible yet. It should be exposed soon though, so I'll leave the issue open to keep this in mind.

**Comment by Khaledgarbaya** [comment]
Following https://github.com/contentful/contentful-space-sync/issues/92
