### ISSUE TITLE
RateLimitExceeded

### ISSUE THREAD

**Issue by matviyiv** [contentful/contentful-space-sync#66]
Every time we run content sync we get this message:

{ sys: { type: 'Error', id: 'RateLimitExceeded' },
  message: "You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan. Please wait a moment before trying the request again."
}

Looks like default timeout between requests is too sort.

**Comment by trodrigues** [comment]
Hi there,

there are two kinds of rate limits in the API, a per second rate, and an hourly rate.

This tool uses our [CMA SDK](https://github.com/contentful/contentful-management.js), which by default handles rate limit errors from the API (and attempts to prevent them by already limiting the amount of requests sent to a number even lower than the actual rate limit).

If a rate limit error is received, it will wait for 3s before retrying, and that period increases on each retry. After five retries if the error keeps being received, it will give up and return the error you're seeing.

So if you are seeing this error, it probably means that you're going over the hourly rate for your organization.

How many entries/assets are in the space you are trying to synchronize? Or are you trying to synchronize the same space multiple times in under that period?

I understand you're also in contact with another of our developers about this via Zendesk, so we'll try to sync when we figure out what's going on and figure out if any improvements are needed on the rate limiting mechanism of the library.

**Comment by trodrigues** [comment]
I am going to close this as this doesn't seem to be a problem related to the tool and this problem is being dealt with through other channels.
