### ISSUE TITLE
Better handling of unpublishing failures

### ISSUE THREAD

**Issue by trodrigues** [contentful/contentful-space-sync#80]
Sometimes when unpublishing on the destination space fails, this might be due to entries that previously failed publishing due to unresolved links errors.

The tool shouldn't abort for these cases and should provide output about the expected course of action (using link-cleaner, etc)

**Comment by nikolaiwu** [comment]
Better solution, by my opinion, would be to, be able to create exact same copy of source space to destination space, regardless of broken links. I don't know if there is some technical difficulties to do that. Right now, we have to convince out client, to clean their references to all unpublished entries, in order for us to create our test environment and keep it synced with production. Our client wants to keep drafts, so they can turn the entries on and off whenever they want. That's proven to be very problematic for our development process. If you have any solutions/ideas/recommendations, please, let me know! Thank you!

**Comment by trodrigues** [comment]
@nikolaiwu that's why we created a separate tool, https://github.com/contentful/contentful-link-cleaner to allow for cleaning those broken links more easily.

The reason why this isn't being done automatically as you suggest, is that we don't want the space sync tool to perform an action that isn't clear, even if it's what some people might want. We prefer to give users the option to solve the situation as they see fit, rather than try to fix for them and leading to situations where what happens might not be what they expect.

It's true that while some of the broken links might exist on purpose, some might be an accident, and some people might want to notice that those broken links exist.

This ticket is essentially about given better feedback back to the users when those situations happen.

**Comment by Khaledgarbaya** [comment]
This issue now is fixed in https://github.com/contentful/contentful-space-sync/commit/65af2d50ec3c36620ab39ea0040b90ed350a9620
