### ISSUE TITLE
Question: Syncing Content Types from "dev" to "prod"

### ISSUE THREAD

**Issue by rossthedevigner** [contentful/contentful-space-sync#82]
_Needs a question label_
I have production space that I want to sync to a dev space to test/build new content types. Once I'm ready to sync my new Content Types from "dev" to "production", will running with the flag `--content-model-only` just copy the schema even though Entries are already published? 

Is there a scenario where Entries could be deleted by doing a `--content-model-only`?

For example; I add 3 new fields to a Content Type in dev that already has published entries in production. When I sync the content model from dev to production, I should see the 3 new (empty) fields in the already published entry in production?

**Comment by trodrigues** [comment]
Hi there,

yes, that would possibly work and the behavior should be the one you describe.

However, that works well if you add fields. If you delete fields, it won't work, as you can only delete fields if there are no entries associated with a content type (there is a workflow for field deletion which works, and it's explained on the README). If you change a field type, you'll also run into problems.

This tool was designed for a one way synchronization workflow, and not for a backwards and forwards workflow, and not only we do not recommend it for such a use case, we also do not intend to support these use cases as the edge cases and possibilities for errors are way too many to consider.

We are currently working on features on the API and User Interface that will allow people to make those sorts of changes possible and will eventually render this tool obsolete.

**Comment by rossthedevigner** [comment]
Excellent, thanks for the additional info. I can't wait to see what you have in store! 👍
