### ISSUE TITLE
Synchronise only one component between two spaces?

### ISSUE THREAD

**Issue by matthieu-beteille** [contentful/contentful-space-sync#86]
Hi,

Let's say I have two spaces with the exact same content types, and some different entries. Would it be possible to keep in sync only some entries? 

Ideally, I'd like to be able to run sth like: 

```contentful-space-sync --config config.js --entry entryID```

(where `config.js` would contain sourceSpace, destinationSpace, and the tokens)

This would synchronise my entry entryId from the source space to the destination space. If the entry doesn't exist it would create it (creating all the nested entries and assets as well). If it does, it would just update it.

Thanks.

Let me know if it's not clear.

**Comment by trodrigues** [comment]
Hi there,

right now, no, this isn't possible.

We've been noticing that many users of this tool seem to have some very specific use cases, so we're looking into potentially documenting the underlying libraries a bit better and give people a sort of framework to let them create more specific tools. Right now I can't give you an exact timeframe of when this might happen.

If this is something that'd be very critical or urgent for you and you'd like to fork the code let me know and I can give you some tips on how this could be done.

**Comment by matthieu-beteille** [comment]
Hey @trodrigues,

Thanks for getting back to me. Indeed, I think I'll need to fork the code at some point in the next month to do this. So if you have any tips on how I could get started, that would be much appreciated!

Thank you so much.

**Comment by Khaledgarbaya** [comment]
Hi @matthieu-beteille,
Let me know if you need to some help for this I would be glad to help.
I would suggest that you take a look over the [transform](https://github.com/contentful/contentful-batch-libs/blob/master/lib/transform/transformers.js), there you will have access to all entries and you can perform some changes to it before pushing it to the destination space
Best,
Khaled

**Comment by Khaledgarbaya** [comment]
I am closing this issue since it's been there for a long time without further activity
