### ISSUE TITLE
version mismatch errors when performing syncs

### ISSUE THREAD

**Issue by j2d3** [contentful/contentful-space-sync#91]
When attempting to perform a sync between two contentful spaces, I keep receiving "version mismatch" errors.

**Comment by Khaledgarbaya** [comment]
Hi @j2d3 ,
Can you please provide more infos like 
- The command you executed and include log file if there is any created. 
- Where did you receive this error.
- What is the version of the space sync tool you used.
- you node version 

**Please don't mention anything related to spaceId or tokens here**

**Comment by Khaledgarbaya** [comment]
Hi I am closing this issue since there was now answer for a long time, feel free to open a new one
