### ISSUE TITLE
Editor interfaces are not sync properly

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful-space-sync#92]
Syncing the Editor interface (representation of the fields) is not done by the tool we should investigate that and add it since the editor interface feature is added in the contentful-management sdk already

**Comment by richhiggins** [comment]
+ 1

**Comment by knupska** [comment]
This is also something that we require.

We've produced a template space of basic content types that we'd like to use for the scaffolding of new spaces, and currently it's a time consuming manual task via the Contentful UI to go through and reimplement field appearance and help text.

**Comment by Khaledgarbaya** [comment]
@knupska and @richhiggins Hi guys, Editor interfaces exporting and importing and more features are added to the our new tools [contentful-export](https://github.com/contentful/contentful-export) and [contentful-import](https://github.com/contentful/contentful-import). You can use these tools for now until we bring the editorInterfaces syncing to the sync tool
