### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DonFuego** [contentful/contentful-space-sync#95]
Trying to sync content-model-only=true from DEV to QA space.  Getting this error...config is:

`{
  "sourceSpace": "xxxx",
  "destinationSpace": "xxxx",
  "sourceDeliveryToken": "xxxx",
  "managementToken": "xxxx",
  "content-model-only": true
}`

First few lines of error: 

`ERR! Failed with
 TypeError: undefined is not a function
ERR! Failed with
     at getFieldEntriesIndex (/usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/get/sort-entries.js:77:18)
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/get/sort-entries.js:61:18
ERR! Failed with
     at arrayMap (/usr/local/lib/node_modules/contentful-space-sync/node_modules/lodash/_arrayMap.js:16:21)
ERR! Failed with
     at map (/usr/local/lib/node_modules/contentful-space-sync/node_modules/lodash/map.js:50:10)
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/get/sort-entries.js:60:36
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/lodash/_baseMap.js:17:23
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/lodash/_createBaseFor.js:17:11
ERR! Failed with
     at baseForOwn (/usr/local/lib/node_modules/contentful-space-sync/node_modules/lodash/_baseForOwn.js:13:20)`

**Comment by Khaledgarbaya** [comment]
Hi @DonFuego 
can you tell me which version you are using and if the space QA is an empty space or has some content already

**Comment by DonFuego** [comment]
Hi @Khaledgarbaya I'm using version 4.0.10.  The QA space is brand new and completely empty - no content or models.

**Comment by DonFuego** [comment]
@Khaledgarbaya FWIW I'm using Node v6.8.0 which used a later version of lodash.  We just tried to run this on Node v5.6.0 and it worked...

**Comment by Khaledgarbaya** [comment]
@DonFuego ah thanks a lot, I will check that
