### ISSUE TITLE
AssetProcessingTimeout exception

### ISSUE THREAD

**Issue by sejoker** [contentful/contentful-space-sync#98]
We started to upload video assets into Contentful. As a result, our contentful-space-sync started to throw "AssetProcessingTimeout: Asset is taking longer then expected to process". Similar to approach I used [here](https://github.com/contentful/contentful-space-sync/issues/96#issuecomment-258138171) I have overridden
```
const ASSET_PROCESSING_CHECK_WAIT = 500
const ASSET_PROCESSING_CHECK_RETRIES = 5
```
from [here](https://github.com/contentful/contentful-management.js/blob/52fe27f1c837ce33b547d6c0bfc6fd503e1bd8eb/lib/entities/asset.js#L23) with increased values and sync started to work again.

It would be great to allow passing assets default timeouts to `contentful-space-sync` directly.

**Comment by sejoker** [comment]
The video files we upload could have 20-200 MB size.

**Comment by sejoker** [comment]
@cc @Khaledgarbaya, would be great to get your feedback on my feature request.

**Comment by Khaledgarbaya** [comment]
Hi @sejoker,
Yeah I guess it kinda make sense and the the [processForAllLocale](https://github.com/contentful/contentful-management.js/blob/52fe27f1c837ce33b547d6c0bfc6fd503e1bd8eb/lib/entities/asset.js#L81) already accepts those params.
It is easy to add to the sync tool, but unfortunately I don't have time for it for now, but hey pull requests are always welcome and I can guide you where to add the changes.

Best,
Khaled
